/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./../components/ActionMenu.vue')['default']
    ChatHeader: typeof import('./../components/ChatHeader.vue')['default']
    ChatInput: typeof import('./../components/ChatInput.vue')['default']
    ChatMessageList: typeof import('./../components/ChatMessageList.vue')['default']
    ChatPage: typeof import('./../components/ChatPage.vue')['default']
    Content: typeof import('./../components/Content.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu.vue')['default']
    FloatButton: typeof import('./../components/FloatButton.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    InviteInput: typeof import('./../components/InviteInput.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    LoadingFloat: typeof import('./../components/LoadingFloat.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./../components/Setting.vue')['default']
    SettingModal: typeof import('./../components/SettingModal.vue')['default']
  }
}
